//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFUserClient.UserReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ConnectedTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConnectedTimesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFUserClient.UserReference.User[] FriendsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFUserClient.UserReference.User[] PendingFriendshipRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFUserClient.UserReference.ChatMessage[] UnreadMessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ConnectedTime {
            get {
                return this.ConnectedTimeField;
            }
            set {
                if ((this.ConnectedTimeField.Equals(value) != true)) {
                    this.ConnectedTimeField = value;
                    this.RaisePropertyChanged("ConnectedTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConnectedTimes {
            get {
                return this.ConnectedTimesField;
            }
            set {
                if ((this.ConnectedTimesField.Equals(value) != true)) {
                    this.ConnectedTimesField = value;
                    this.RaisePropertyChanged("ConnectedTimes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFUserClient.UserReference.User[] Friends {
            get {
                return this.FriendsField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendsField, value) != true)) {
                    this.FriendsField = value;
                    this.RaisePropertyChanged("Friends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFUserClient.UserReference.User[] PendingFriendshipRequest {
            get {
                return this.PendingFriendshipRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.PendingFriendshipRequestField, value) != true)) {
                    this.PendingFriendshipRequestField = value;
                    this.RaisePropertyChanged("PendingFriendshipRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFUserClient.UserReference.ChatMessage[] UnreadMessages {
            get {
                return this.UnreadMessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnreadMessagesField, value) != true)) {
                    this.UnreadMessagesField = value;
                    this.RaisePropertyChanged("UnreadMessages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChatMessage", Namespace="http://schemas.datacontract.org/2004/07/Domain")]
    [System.SerializableAttribute()]
    public partial class ChatMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TheMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WCFUserClient.UserReference.User TheUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Display {
            get {
                return this.DisplayField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayField, value) != true)) {
                    this.DisplayField = value;
                    this.RaisePropertyChanged("Display");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TheMessage {
            get {
                return this.TheMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.TheMessageField, value) != true)) {
                    this.TheMessageField = value;
                    this.RaisePropertyChanged("TheMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFUserClient.UserReference.User TheUser {
            get {
                return this.TheUserField;
            }
            set {
                if ((object.ReferenceEquals(this.TheUserField, value) != true)) {
                    this.TheUserField = value;
                    this.RaisePropertyChanged("TheUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserReference.IUser")]
    public interface IUser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/SaveUser", ReplyAction="http://tempuri.org/IUser/SaveUserResponse")]
        bool SaveUser(WCFUserClient.UserReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/SaveUser", ReplyAction="http://tempuri.org/IUser/SaveUserResponse")]
        System.Threading.Tasks.Task<bool> SaveUserAsync(WCFUserClient.UserReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUsers", ReplyAction="http://tempuri.org/IUser/GetUsersResponse")]
        WCFUserClient.UserReference.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/GetUsers", ReplyAction="http://tempuri.org/IUser/GetUsersResponse")]
        System.Threading.Tasks.Task<WCFUserClient.UserReference.User[]> GetUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ModifyUser", ReplyAction="http://tempuri.org/IUser/ModifyUserResponse")]
        bool ModifyUser(WCFUserClient.UserReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/ModifyUser", ReplyAction="http://tempuri.org/IUser/ModifyUserResponse")]
        System.Threading.Tasks.Task<bool> ModifyUserAsync(WCFUserClient.UserReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/DeleteUser", ReplyAction="http://tempuri.org/IUser/DeleteUserResponse")]
        bool DeleteUser(WCFUserClient.UserReference.User user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUser/DeleteUser", ReplyAction="http://tempuri.org/IUser/DeleteUserResponse")]
        System.Threading.Tasks.Task<bool> DeleteUserAsync(WCFUserClient.UserReference.User user);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserChannel : WCFUserClient.UserReference.IUser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserClient : System.ServiceModel.ClientBase<WCFUserClient.UserReference.IUser>, WCFUserClient.UserReference.IUser {
        
        public UserClient() {
        }
        
        public UserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveUser(WCFUserClient.UserReference.User user) {
            return base.Channel.SaveUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> SaveUserAsync(WCFUserClient.UserReference.User user) {
            return base.Channel.SaveUserAsync(user);
        }
        
        public WCFUserClient.UserReference.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<WCFUserClient.UserReference.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
        
        public bool ModifyUser(WCFUserClient.UserReference.User user) {
            return base.Channel.ModifyUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> ModifyUserAsync(WCFUserClient.UserReference.User user) {
            return base.Channel.ModifyUserAsync(user);
        }
        
        public bool DeleteUser(WCFUserClient.UserReference.User user) {
            return base.Channel.DeleteUser(user);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteUserAsync(WCFUserClient.UserReference.User user) {
            return base.Channel.DeleteUserAsync(user);
        }
    }
}
